FROM alpine:3.12

RUN apk update && apk add nginx openrc --no-cache openssl
RUN apk add telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache


COPY srcs/telegraf.conf /etc/telegraf/telegraf.conf
COPY ./srcs/ .

EXPOSE 80 443

ENTRYPOINT ["sh", "script.sh"]
