apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
  - name: phpmyadmin
    port: 5000
    protocol: TCP
  selector:
    run: phpmyadmin
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    matchLabels:
      run: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        run: phpmyadmin
    spec:
      restartPolicy: Always
      containers:
      - name: phpmyadmin
        imagePullPolicy: Never
        image: phpmyadmin-image
        ports:
        - name: phpmyadmin
          containerPort: 5000
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: volume