apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grafana
  template:
    metadata:
      labels:
        run: grafana
    spec:
      containers:
      - containers:
        name: grafana
        image: grafana-image
        imagePullPolicy: Never
      restartPolicy: Always