apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  creationTimestamp: null
  generation: 1
  labels:
    app: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      run: influxdb
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: influxdb
    spec:
      restartPolicy: Always
      containers:
        - image: influxdb-image
          imagePullPolicy: Never
          name: influxdb
          ports:
            - containerPort: 8086
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-data-storage
      volumes:
        - name: influxdb-data-storage
          persistentVolumeClaim:
            claimName: influxdb-data
