apiVersion: v1  
kind: Service  
metadata:  
  name: influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:  
  selector:  
    run: influxdb
    type: ClusterIP
  ports:  
    - protocol: TCP
      name: influxdb 
      port: 8086  
      targetPort: 8086